packages:
  - example

nodeLinker: hoisted
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  lefthook: true
overrides:
  uuid@<11.1.1: ^11.1.1
minimumReleaseAgeExclude:
  - uuid@11.1.1
patchedDependencies:
  '@expo/metro-config': patches/@expo__metro-config.patch
